# Generated by Django 4.2.3 on 2023-08-22 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fiber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("addr", models.TextField()),
                ("lng", models.FloatField()),
                ("lat", models.FloatField()),
                ("type", models.TextField()),
            ],
        ),
    ]
