# Generated by Django 4.2.3 on 2023-08-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_talav"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="talav",
            table="talav",
        ),
    ]
