# Generated by Django 4.2.3 on 2023-08-29 08:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_talav_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Natoshi",
            fields=[
                (
                    "GutNo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("gutno", models.IntegerField()),
                ("id", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("gut", models.TextField()),
                ("crop", models.TextField()),
                ("owner", models.TextField()),
                ("remark", models.TextField()),
                ("village", models.TextField()),
                ("area", models.FloatField()),
            ],
            options={
                "db_table": "Natoshi",
                "managed": False,
            },
        ),
    ]
